### ISSUE TITLE
Problem: Need to run more than xbps-src on the builder

### ISSUE THREAD

**Issue by Vaelatern** [dxpb/dxpb#12]
Solution: Add a shell script from the commands from https://github.com/void-linux/void-infrastructure/blob/master/ansible/roles/buildmaster/templates/master.cfg.j2 as a single shell script, probably with arguments, to be run on the `dxpbuilder` side of things.

**Comment by bobertlo** [comment]
Based on this, I created https://github.com/bobertlo/xbps-bulk-builder

It's basically just a wrapper to `xbps-bulk` which can clone it's own void-packages and create a bootstrap if they are not preset already. It can also use xbps-bulk features `-N` to disable remote dependency resolution and `-t` to make temporary masterdir bind mounts. Each build is run in it's own directory, and if none are specified (`-b builddir`) it just uses `builddir` and cleans it out each run.

Cross targets right now require you to `XBPS_TARGET_ARCH xbps-install -S` to get the repocache for that arch. I don't know if there's a better way to do that. Also, mixing glibc/musl hosts and bootstraps also is finnickey and I haven't been able to document how to do so in a stable procedure ;)

I could PR this if you want. Not sure where exactly it would live. I think this is as far as this can be developed until dxpbuilder's are starting to use it.

**Comment by Vaelatern** [comment]
Fantastic! I don't know where to put it in this repo either, I think under `/assets/` is the most go-idiomatic place to put it. So perhaps at `/assets/builder/`

**Comment by Vaelatern** [comment]
Also adding that summary you just wrote to the commit message would be amazing, when you do PR it.

**Comment by bobertlo** [comment]
Will do. I'll do a little more testing tonight first, to make sure it's not just working on my laptop! And to avoid potential unnecessary traffic on this repo.

**Comment by bobertlo** [comment]
For the record #14 only adds [-R repo] to pass a repo to xbps-checkvers and [-c conf] to pass a config file to etc/conf for xbps-src.

I just wanted to test it a little because I rewrote the front-end in a Starbucks on my laptop.
