### ISSUE TITLE
Problem: Can't get started by reading documentation

### ISSUE THREAD

**Issue by bobertlo** [dxpb/dxpb#29]
This problem may be better to address once things are more functional, but here is a checklist of my first ideas for documentation:

Solutions:
- [ ] document how to use the dxpbd build master
  - [x] document dxpbd.yml options
  - [ ] document metrics collection
- [ ] document how to setup the builders
  - [x] document dxpbuilder.yml options
  - [ ] document how to use xbps-bulk-builder.sh
  - [ ] document non-obvious target arguments for xbps-bulk

**Comment by Vaelatern** [comment]
@bobertlo Is this closable due to #31?

I want to, for this repo, to not include issue/PR numbers in commits wherever possible, so manual closing is better.

**Comment by bobertlo** [comment]
I think #32 can make this closeable. Didn't want to close before cleaning up a bit. I had my own home directory in there and the scripts were referenced as `./poke_xbulk.sh` and `./assets/builder/...`

**Comment by Vaelatern** [comment]
Thanks!
