### ISSUE TITLE
Use of raw channel instead of a queue.

### ISSUE THREAD

**Issue by the-maldridge** [dxpb/dxpb#4]
https://github.com/dxpb/dxpb/blob/1729ae64c34c0f1b4329b1d5563da416feda6d2d/cmd/dxpbd/main.go#L13

While managing raw channels is a fine solution, you might consider using a higher level abstraction since its pretty clear here that what you want is a queue.  https://github.com/Workiva/go-datastructures provides a nice queue implementation that uses waitgroups internally to block on empty queues during a dequeue call.

**Comment by Vaelatern** [comment]
I was thinking of replacing with RPC

**Comment by the-maldridge** [comment]
I assumed this channel was used in process, where RPC wouldn't make much sense.  If this is instead used IPC then sure, RPC would be a fine solution.

**Comment by Vaelatern** [comment]
Only resistance to using a queue is that this is somewhat placeholder, so I'm not going to polish it too much while the rest of the daemon is still being constructed around our ears.

**Comment by the-maldridge** [comment]
Then make this channel buffered, as is you can lock up parts of the application.

**Comment by Vaelatern** [comment]
Closed because the use of RPC means the RPC library handles queuing where doable.
