### ISSUE TITLE
GitHub webhooks have integrity checks.

### ISSUE THREAD

**Issue by the-maldridge** [dxpb/dxpb#5]
https://github.com/dxpb/dxpb/blob/1729ae64c34c0f1b4329b1d5563da416feda6d2d/internal/app/webhook_target/daemon.go#L11

GitHub's webhooks are signed and contain a very specific schema.  Unless you intend to re-implement this integrity checking yourself, I highly recommend the use of a library: https://github.com/go-playground/webhooks

**Comment by Vaelatern** [comment]
2a6999b48a17
