### ISSUE TITLE
Connects to IRC by default

### ISSUE THREAD

**Issue by bobertlo** [dxpb/dxpb#8]
I'm sorry, I tried to look into the code and also viper, but can't tell if there is a way to detect whether IRC is specified or not in the config file. It would be nice for testers/(future users) to not always try to connect to IRC, not that it's doing any harm.

I spent a little while looking, but I can't figure it out. I feel you guys could solve this quickly or tell me if i'm mistaken even more quickly.

**Comment by Vaelatern** [comment]
Right now it hardly does anything except connect to IRC :)

**Comment by bobertlo** [comment]
I understand :) I did notice that I did not spam #dxpb with a config with the 'irc' section removed. I'm trying to come up to speed, and am lost on this minor issue, so I put it here!

**Comment by Vaelatern** [comment]
Sure, I'll add the capability to not do this

**Comment by bobertlo** [comment]
I normally would always prefer to submit a PR rather than issue, but I am out of my depth :)

**Comment by Vaelatern** [comment]
8731b13
